version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/src
      - /usr/src/quasar-project/node_modules
    command:  quasar dev
    environment:
      MONGO_URL: "mongodb://db:27017/test"